<div class="col-md-4">
    <div class ="text-center">
    <h2><?=$this->getUserName()?></h2>
    </div>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
        condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis
        euismod. Donec sed odio dui. </p>
    <form action="<?=$this->getLink()?> " method="post" class="navbar-form navbar-right">
        <button  type="submit" class="btn btn-success">View</button>
    </form>
</div>