<?php
/** @var model\Info $this */
?>
<div class="text-uppercase">
    <!--<div>-->
    <!--    <img src="public/img/img_3.png" alt="img">-->
    <!---->
    <!--</div>-->

    <div class="square1">
        <h1>Personal </h1>
        <h2>Name: <?= $name . " " . $secondName ?> </h2>
        <h2>City: <?= $city ?></h2>
    </div>
    <div>
        <h1>Education</h1>
        <h2>Place: <?= $place ?></h2>
        <h2>Period: <?= $period ?></h2>
        <h2>Speciality: <?= $speciality ?></h2>
    </div>
    <div>
        <h1>Experience</h1>
        <h2>Company: <?= $company ?></h2>
        <h2>Period: <?= $period ?></h2>
        <h2>Position: <?= $position ?></h2>
    </div>
    <div>
        <h1>Contacts</h1>
        <h2>Email: <?= $email ?></h2>
        <h2>LinkedIn: <?= $linkedin ?></h2>
        <h2>GitHub: <?= $github ?></h2>
        <h2>Phone: <?= $phone ?></h2>
    </div>
</div>

</div>


</div>