
<form action="http://brief/registration/secondstep" class="center-block" method="post" >
    <fieldset class="form-control-static center-block">
        <fieldset class="center-block">
            <label for="name">Second Name</label><p class="input"><input name="secondName"  ></p>
            <label for="password">Email</label><p class="input"><input type="email" name="email"   ></p> <!-- pattern="[^А-Яа-я]+$"  - маска ввода пароля -->
            <label for="re-password">Phone Number</label><p class="input"><input type="tel" name="phoneNumber" id="re-password" ></p> <!-- pattern="[^А-Яа-я]+$"  - маска ввода пароля -->
            <label for="name">Your salary</label><p class="input"><input name="salary"  ></p>
            <label for="name">Are you perfomer?</label><p class="input"><input type="checkbox" name="executer"  ></p>

        </fieldset>
    </fieldset>
    <button  type="submit" class="btn btn-success"  >Registration</button>
</form>