<div id="navbar" class="navbar-collapse collapse">
    <form action="http://brief/registration" method="post" class="navbar-form navbar-right">
        <button  type="submit" class="btn btn-success">Registr</button>
    </form>
    <form action="http://brief/admin/auth" method="post" class="navbar-form navbar-right">
        <div class="form-group">
            <input type="text" placeholder="Email" name="Nickname" class="form-control">
        </div>
        <div class="form-group">
            <input type="password" placeholder="Password" name="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
    </form>


</div>
<!--/.navbar-collapse -->
.







































